#! /bin/bash

if [[ -x $(which $CC) ]]
then
  echo "Using c-compiler $CC"
else
  if [[ -x $(which clang-12) ]]
  then
    export CC=clang-12
  else
    echo "$0: requires clang-12 or env var CC to be executable"
    exit 1
  fi
fi

set -ex

MAKE_FLAGS="ARCH=arm64 CC=$CC CROSS_COMPILE=aarch64-linux-gnu-"

# config for CN build of pKVM

make $MAKE_FLAGS defconfig

./scripts/config -e CONFIG_EXPERT
./scripts/config -d CONFIG_BUG
./scripts/config -d CONFIG_GENERIC_BUG
./scripts/config -d CONFIG_GENERIC_BUG_RELATIVE_POINTERS

# there is probably a much better way to do this next bit

yes '' | make $MAKE_FLAGS syncconfig

time make $MAKE_FLAGS -j $(nproc) arch/arm64/kvm/hyp/nvhe/

python3 compile_cmd.py make



