#!/usr/bin/env sh

disableUndef() {
    if [ "$(./scripts/config -k -s $1)" = "undef" ]; then
        ./scripts/config -k -d $1
    fi
}

# reset ghost config options to a sensible default

disableUndef CONFIG_NVHE_GHOST_SPEC_NOISY
disableUndef CONFIG_NVHE_GHOST_SPEC_VERBOSE
disableUndef CONFIG_NVHE_GHOST_SPEC_DUMP_STATE

disableUndef CONFIG_NVHE_GHOST_SPEC_SAFETY_CHECKS

disableUndef CONFIG_NVHE_GHOST_SPEC_NOISY
disableUndef CONFIG_NVHE_GHOST_SPEC_COLOURS

disableUndef CONFIG_NVHE_GHOST_DIFF
disableUndef CONFIG_NVHE_GHOST_DIFF_post_computed
disableUndef CONFIG_NVHE_GHOST_DIFF_pre_post_recorded
disableUndef CONFIG_NVHE_GHOST_DIFF_post_host_pgtable

disableUndef CONFIG_NVHE_GHOST_SPEC_CHECK_handle_host_mem_abort
disableUndef CONFIG_NVHE_GHOST_SPEC_NOISY_handle_host_mem_abort
disableUndef CONFIG_NVHE_GHOST_SPEC_CHECK___pkvm_host_share_hyp
disableUndef CONFIG_NVHE_GHOST_SPEC_CHECK___pkvm_host_unshare_hyp
disableUndef CONFIG_NVHE_GHOST_SPEC_CHECK___pkvm_host_reclaim_page
disableUndef CONFIG_NVHE_GHOST_SPEC_CHECK___pkvm_host_map_guest
disableUndef CONFIG_NVHE_GHOST_SPEC_CHECK___kvm_vcpu_run
disableUndef CONFIG_NVHE_GHOST_SPEC_CHECK___pkvm_init_vm
disableUndef CONFIG_NVHE_GHOST_SPEC_CHECK___pkvm_init_vcpu
disableUndef CONFIG_NVHE_GHOST_SPEC_CHECK___pkvm_teardown_vm
disableUndef CONFIG_NVHE_GHOST_SPEC_CHECK___pkvm_vcpu_load
disableUndef CONFIG_NVHE_GHOST_SPEC_CHECK___pkvm_vcpu_put
disableUndef CONFIG_NVHE_GHOST_SPEC_CHECK___pkvm_guest_share_host
disableUndef CONFIG_NVHE_GHOST_SPEC_CHECK___pkvm_guest_unshare_host
disableUndef CONFIG_NVHE_GHOST_SPEC_CHECK_handle_guest_mem_abort
disableUndef CONFIG_NVHE_GHOST_SPEC_NOISY_handle_guest_mem_abort

disableUndef CONFIG_NVHE_GHOST_SIMPLIFIED_MODEL
disableUndef CONFIG_NVHE_GHOST_SIMPLIFIED_MODEL_NOISY
disableUndef CONFIG_NVHE_GHOST_SIMPLIFIED_MODEL_NOISY_CONDENSED
disableUndef CONFIG_NVHE_GHOST_SIMPLIFIED_MODEL_DUMP_ON_TRANS
disableUndef CONFIG_NVHE_GHOST_SIMPLIFIED_MODEL_DIFF_ON_TRANS

disableUndef CONFIG_NVHE_GHOST_SPEC_INJECT_ERROR___kvm_tlb_flush_vmid_ipa_MISSING_TLBI
disableUndef CONFIG_NVHE_GHOST_SPEC_INJECT_ERROR_kvm_clear_pte_MISSING_WRITE
disableUndef CONFIG_NVHE_GHOST_SPEC_INJECT_ERROR_stage2_map_walker_try_leaf_MISSING_BREAK
disableUndef CONFIG_NVHE_GHOST_SPEC_INJECT_ERROR_stage2_try_break_pte_MISSING_TLBI
disableUndef CONFIG_NVHE_GHOST_SPEC_INJECT_ERROR_stage2_put_pte_MISSING_INVALIDATE

disableUndef CONFIG_NVHE_GHOST_SPEC_INJECT_FIX_stage2_try_break_pte_MISSING_DSB
