#ifndef __PICOVM_CONFIG_H
#define __PICOVM_CONFIG_H

#define PICOVM_CONFIG_GRANULE_SIZE  (UL(0) << 14) // 4K size
#define PICOVM_CONFIG_IA_BITS	    48
#define PICOVM_CONFIG_ARM64_PA_BITS 48

#define PICOVM_CONFIG_STARTING_LEVEL	 0
#define PICOVM_CONFIG_NVHE_EL2_STACKSIZE 1

#endif /* __PICOVM_CONFIG_H */
