#!/bin/zsh

. ${0:a:h}/config.sh

# brew install make     <--- for `gmake`

# macOS does not have nproc (unless GNU coreutils is installed)
NPROC=$(sysctl -n hw.physicalcpu)

# if available use https://ccache.dev/ (speeding up recompilation)
if type 'ccache' > /dev/null; then
  WRAPPED_CLANG="ccache ${CLANG}"
else
  WRAPPED_CLANG="${CLANG}"
fi

vars=(
  ARCH=arm64
  CROSS_COMPILE=aarch64-none-elf-
  # LD=ld.lld
  CC=${CC:-${WRAPPED_CLANG}}
  # INSTALL_PATH=${install}/boot
  # INSTALL_MOD_PATH=${install}
  # CPATH="$CPATH:/Volumes/Dev-tools/arm-gnu-toolchain/arm-gnu-toolchain-13.2.Rel1-darwin-arm64-aarch64-none-elf/aarch64-none-elf/include"
)

# making sed point to gnu-sed and putting local GNU binaries first
PATH="/opt/homebrew/opt/gnu-sed/libexec/gnubin:${0:a:h}/bin:$PATH"

exec gmake LLVM=1 \
  HOSTCFLAGS="-D_UUID_T -D__GETHOSTUUID_H -I${0:a:h}/include" \
  HOSTLDFLAGS="-L/opt/homebrew/opt/openssl/lib" \
  $vars -j ${NPROC} "${@}"
  # HOSTCFLAGS="-D_UUID_T -D__GETHOSTUUID_H -I/Volumes/Dev-tools/linux-kernel-env/include" \
  # $vars -j ${NPROC} "${@}"
